### ISSUE TITLE
Invalid attribute length

### ISSUE THREAD

**Issue by LaStrada** [ashald/home-assistant-lywsd02#10]
This suddenly didn't work. Not sure what happened, but my automation did work in the end of October.

Example from the developer tools:
```
action: lywsd02.set_time
data:
  mac: "E7:2E:01:xx:xx:xx"
  timestamp: 1734130022
  tz_offset: 1
  temp_mode: C
  clock_mode: 24
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/lywsd02/__init__.py:83
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:47:32 (2 occurrences)
Last logged: 23:47:46

[139868632201776] Error handling message: Unknown error (unknown_error) Ståle from 10.0.0.213 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.12.1 (io.robbie.HomeAssistant; build:2024.1041; iOS 18.2.0) Mobile/HomeAssistant, like Safari)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 78, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 602, in write_gatt_char
    await self._client.bluetooth_gatt_write(
        self._address_as_int, characteristic.handle, bytes(data), response
    )
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 838, in bluetooth_gatt_write
    await self._bluetooth_gatt_write(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 876, in _bluetooth_gatt_write
    await self._send_bluetooth_message_await_response(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 484, in _send_bluetooth_message_await_response
    raise BluetoothGATTAPIError(BluetoothGATTError.from_pb(resp))
aioesphomeapi.core.BluetoothGATTAPIError: Bluetooth GATT Error address=E7:2E:01:xx:xx:xx handle=62 error=13 description=Invalid attribute length

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg.get("variables"), context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lywsd02/__init__.py", line 83, in set_time
    await client.write_gatt_char(_UUID_TIME, data_clock_mode)
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 786, in write_gatt_char
    await self._backend.write_gatt_char(characteristic, data, response)
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 105, in _async_wrap_bluetooth_operation
    raise BleakError(str(ex)) from ex
bleak.exc.BleakError: Bluetooth GATT Error address=E7:2E:01:xx:xx:xx handle=62 error=13 description=Invalid attribute length

```

**Comment by smrtprjcts** [comment]
Hi @LaStrada ,
Has the 12/24 hour switch ever worked for you? Or for you @ashald?
It's not working for me with firware 1.1.2_0042.

**Comment by LaStrada** [comment]
Yes this exact action/parameters (of course different timestamp) has been working for a while, including the last time we adjusted the time in October. It suddenly worked again once last week, but haven't been able to make it work after that.

**Comment by smrtprjcts** [comment]
Which  firmware?

**Comment by robloh** [comment]
I've been having the same issue. Setting 12 hour clock has never worked and always errors out with the above. Setting time w/o the clock mode works fine. I'm not able to get the firmware version (Mi home app is set to US region)  but in case it's helpful the full model number for mine is LYWSD02MMC


Side note: I am connected to it through an ESPHome ESP32 bluetooth proxy (connected over ethernet, not wifi), not a bluetooth dongle on my HASS machine

**Comment by joaopedros2** [comment]
I'm also getting errors when trying to execute the action.

```Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/lywsd02/__init__.py:76
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:57:36 PM (2 occurrences)
Last logged: 11:57:36 PM

[139703515997248] Error handling message: Unknown error (unknown_error) João Silva from 176.79.60.190 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg.get("variables"), context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1828, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 556, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 524, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1009, in _async_step_call_service
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lywsd02/__init__.py", line 76, in set_time
    async with BleakClient(ble_device, timeout=tout) as client:
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 570, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.13/site-packages/habluetooth/wrappers.py", line 328, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 254, in connect
    assert_reply(reply)
    ~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation already in progress```

**Comment by ashald** [comment]
I've got 6 of these clocks:
* 4 showing up as LYWSD02 (hardware revision `miaomiaoce.sensor_ht.t1`)
* 2 showing up as LYWSD02MMC (hardware revision `miaomiaoce.sensor_ht.t8`)

Using the native Xiaomi app, I couldn't find a way to switch time format between 12/24. Not sure if I'm missing something, if it's automatic based on system settings, or if it's simply not supported on these clocks.

The 12/24 switch feature was contributed to this plugin by @lranders - would be great to hear from them where did they get the insights about it.

Wondering if anyone saw these clocks showing time in AM/PM format? Or if it's 24h only and we can drop the parameter to avoid confusion?

**Comment by ashald** [comment]
@joaopedros2 your issue is simply due to insufficient timeout (or low battery) - try increasing the timeout to few minutes, and/or replace the battery. It's not related to this issue so let's avoid noise in the conversation.

**Comment by lranders** [comment]
> The 12/24 switch feature was contributed to this plugin by [@lranders](https://github.com/lranders) - would be great to hear from them where did they get the insights about it.
> 
> Wondering if anyone saw these clocks showing time in AM/PM format? Or if it's 24h only and we can drop the parameter to avoid confusion?

I got a nRF52840 which I put in monitor-mode and captured the traffic from the Mi home app via Wireshark.

I can't speak to the non-MMC display, but the MMC definitely does 12/24 hour display.

**Comment by lranders** [comment]
@ashald I hope it's not dependent on firmware version, but I can check if you think it's required.

**Comment by LaStrada** [comment]
I did some more testing. This integration works perfectly after midnight, but not during the day. Not tested this _every_ hour, but I can set up a test for 24 hours.

FW: 1.1.2_0097
HW: F2_WF
(From nRF Connect)

I don't use the app anymore, only through HA. No need for the app as long as this integration can update the time zone change twice a year.

I can try to look into the data sent from the app and compare.

**Comment by lranders** [comment]
@LaStrada Please do; they might have snug in a change to the package format. Wireshark will make the change obvious real fast.

**Comment by skiblawi** [comment]
I’m getting the same errors, but I am not trying to set clock mode or tz offset. I have an automation set to run every Sunday after midnight and I know it works occasionally because the time hasn’t strayed like it did before I set up the automation. But most of the time it fails. 

I also try to set it every time HA’s timezone changes, but it always fails while testing this automation.

**Comment by LaStrada** [comment]
Sorry, this took a while. I don't have the choice to switch between 12/24 hours in the app. I find temperature unit, but nothing else... Any ideas where to find it?

**Comment by LaStrada** [comment]
Can people with the non-MMC version check if you have this choice in the app and/or if changing 12/24h fails with this integration?

Maybe this just needs to be disabled for this device? I had a MMC-version as well, but this device has died lately (not able to connect to it anymore).

**Comment by ashald** [comment]
Root cause: the 12/24-hour write is malformed. `clock_mode` packs **7 bytes** (`struct.pack('IHB', 0, 0, ...)`) and writes them to the time characteristic `EBE0CCB7-…`, which only accepts **5 bytes** (`struct.pack('Ib', timestamp, tz_offset)`). The device rejects the wrong length with `error=13 Invalid attribute length`, which matches every report here. Plain time sync (the 5-byte write) is unaffected — that is why setting time *without* `clock_mode` works.

This is independent of the BLE-reliability fixes in v0.3.0. I have not been able to confirm a working 12/24 command across the LYWSD02 vs LYWSD02MMC variants/firmwares (I cannot even find the toggle in the Xiaomi app for my non-MMC units), so I am inclined to either fix the packing once someone captures a known-good command, or remove/guard the `clock_mode` parameter so it stops throwing. Leaving this open to track that decision — if anyone has a Wireshark capture of the official app switching 12/24 on their model, please post it.

**Comment by lranders** [comment]
@ashald Let me see if I can dig out the original Wireshark capture for you...

**Comment by lranders** [comment]
@ashald Well, the originals were lost to time, so here is a capture taken today:

[lywsd02mmc.pcapng.gz](https://github.com/user-attachments/files/32430678/lywsd02mmc.pcapng.gz)

<img width="1600" height="900" alt="Image" src="https://github.com/user-attachments/assets/c351920f-cb1a-4bee-9d70-d1de3bbb4141" />

<img width="550" height="78" alt="Image" src="https://github.com/user-attachments/assets/4bf86a40-9a1d-48bd-a021-96f3d8cc91e4" />

As you can see, it's clearly writing **7 bytes** to the attribute.

For completeness, here is the personality information:
Hardware version **F3_A1**,
Firmware version **2.0.1_0060**.

**Comment by ashald** [comment]
Thanks @lranders — decoded your capture (`lywsd02mmc.pcapng`), and it's conclusive:

- Two 7-byte writes to `ebe0ccb7` (the time characteristic): `00 00 00 00 00 00 aa` = 12h, `00 00 00 00 00 00 00` = 24h — **byte-for-byte identical to what this integration already sends**. There are no ATT error responses anywhere in the capture, so the MMC accepts them fine.
- So the payload was never the problem. The failures are **model-specific**: on the LYWSD02MMC `ebe0ccb7` accepts this 7-byte clock-format write, but on the plain LYWSD02 the same characteristic is a fixed **5-byte** time attribute, so the 7-byte write is rejected with `Invalid attribute length` — and that previously aborted the entire `set_time` call.

**v0.3.1** keeps the (now-validated) `clock_mode` payload but makes that write **non-fatal**: on a device that rejects it, the time is still set and a warning is logged (`clock_mode is only supported on the LYWSD02MMC`) instead of failing the call. It's now documented as MMC-only in the README, info.md, and the service description.

@lranders — when you get a chance, could you confirm 12/24 switching works through this integration (v0.3.1) on your MMC? I'll close this once confirmed.
